### GET books
GET {{host}}/books

### GET orders
GET {{host}}/orders

### Create book
POST {{host}}/books
Content-Type: application/json

{
  "isbn": "1234567897",
  "title": "All I don't know about the Arctic",
  "author": "Jon Snow",
  "price": 9.9,
  "publisher": "Polarsophia"
}

### Post an order
POST {{host}}/orders
Content-Type: application/json

{
  "isbn": "1234567897",
  "quantity": 3
}
